name: xmonad-ef
version: "0.1.0.0"
github: "endofunky/nix-config"
license: GPL-3.0
author: "Tobias Svensson"
maintainer: "tob@tobiassvensson.co.uk"
copyright: "GPL-3.0"
description: xmonad config

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executable:
  main: xmonad.hs
  dependencies:
    - base >= 4.7 && < 5
    - containers
    - xmonad >= 0.15
    - xmonad-contrib >= 0.15
    - xmonad-extras >= 0.15
    - xmonad-spotify >= 0.1.2.2
